apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allow-specific-ip-range
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: pod-specific-ip-range
    match:
      resources:
        kinds:
        - NetworkPolicy
    validate:
      message: "Network policies must allow traffic from 192.168.0.0/16"
      pattern:
        spec:
          podSelector:
            matchLabels:
              app: myapp
          ingress:
          - from:
            - ipBlock:
                cidr: 192.168.0.0/16