apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-quotas
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: namespace-resource-quotas
    match:
      resources:
        kinds:
        - ResourceQuota
    validate:
      message: "Namespaces must have a CPU limit of 2 and a memory limit of 1 GiB"
      pattern:
        spec:
          hard:
            limits.cpu: "2"
            limits.memory: "1Gi"