apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pod-labels
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: pod-labels
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Pods must have a 'tier' label with a value of 'backend'"
      pattern:
        metadata:
          labels:
            tier: backend