apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-backend-service-account
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: pod-backend-service-account
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Pods must use the 'backend' service account"
      pattern:
        spec:
          serviceAccountName: backend