apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pod-security-policies
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: pod-security-profile
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Pods must use the 'seccomp' and 'apparmor' security profiles"
      pattern:
        spec:
          securityContext:
            seccompProfile:
              type: "RuntimeDefault"
            seLinuxOptions:
              type: "spc_t"
            supplementalGroups:
              - 100
            sysctls:
              - name: net.ipv4.ip_forward
                value: "0"